import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Header from "../components/Header";
import { getToken } from "next-auth/jwt";
import Sidebar from "../components/Sidebar";
import Feed from "../components/Feed";
import Login from "../components/Login";
import { getSession } from "next-auth/react";
import Widgets from "../components/Widgets";

export default function Home({ userSession }) {
  if (!userSession) {
    return <Login />;
  }
  console.log(userSession);
  return (
    <div className="h-screen bg-gray-100 overflow-hidden">
      <Head>
        <title>Facebook 2.0</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />

      <main className="flex  ">
        <Sidebar />
        <Feed />
        <Widgets />
      </main>
    </div>
  );
}

export async function getServerSideProps(context) {
  const userSession = await getSession(context);

  return {
    props: {
      userSession,
    },
  };
}
